package HW5;
import java.awt.*;
import simView.*;

public class calcModel extends ViewableDigraph // gp model
{
	public calcModel()
	{
		super("calcModel"); // 이름바꿈
    	
		// 노드를 생성
		ViewableAtomic g = new user("user", 10);
		ViewableAtomic p = new calc("calc", 10);
    	
		// 노드를 그래프에 표시
		add(g);
		add(p);
  
		// coupling 설정
		addCoupling(g, "out", p, "in");
		addCoupling(p, "out", g, "in");
	}
    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("user")).setPreferredLocation(new Point(409, 231));
        ((ViewableComponent)withName("calc")).setPreferredLocation(new Point(413, 84));
    }
}
