package HW3;
import java.awt.*;
import simView.*;

public class gproc extends ViewableDigraph
{

	public gproc()
	{
		super("gproc");
		
		ViewableAtomic g = new genr("genr", 40);
		ViewableAtomic p = new proc("proc", 50);
		
		add(g);
		add(p);
		
		addCoupling(g, "out", p, "in");
		addCoupling(p, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(768, 448);
        ((ViewableComponent)withName("genr")).setPreferredLocation(new Point(313, 79));
        ((ViewableComponent)withName("proc")).setPreferredLocation(new Point(321, 251));
    }
}
