package Lab7;
import java.awt.*;
import simView.*;

public class handshake extends ViewableDigraph
{

	public handshake()
	{
		super("3-way Handshake"); // gp model의 이름수정
    	
		ViewableAtomic g = new client("client", 10); // client 생성
		ViewableAtomic p = new server("server", 20); // server 생성
    	
		add(g); // 노드추가
		add(p); // 노드추가
  
		addCoupling(g, "out", p, "in"); // 커플링추가
		addCoupling(p, "out", g, "in"); // 커플링추가
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("server")).setPreferredLocation(new Point(44, 292));
        ((ViewableComponent)withName("client")).setPreferredLocation(new Point(50, 50));
    }
}
