package HW4;
import java.awt.*;
import simView.*;

public class gpt extends ViewableDigraph // diagraph model
{

	public gpt()
	{
		super("gpt"); // 전체 그래프 이름
		
		ViewableAtomic g = new genr("g", 10); // sigma를 10으로 설정
		ViewableAtomic p = new proc("p", 20); // sigma를 20으로 설정
		ViewableAtomic t = new transd("t", 420); // sigma(observation time)을 420으로 설정
    	
		add(g); // g노드를 추가
		add(p); // p노드를 추가
		add(t); // t노드를 추가
  
		/* generator의 coupling 설정 */
		addCoupling(g, "out", p, "in"); // g의 out과 p의 in을 연결
		addCoupling(g, "out", t, "ariv"); // g의 out과 t의 ariv를 연결
		
		/* processor의 coupling 설정 */
		addCoupling(p, "out", t, "solved"); // p의 out과 t의 solved를 연결
		
		/* transducer의 coupling 설정 */
		addCoupling(t, "out", g, "in"); // t의 out과 g의 in을 연결
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(694, 481);
        ((ViewableComponent)withName("t")).setPreferredLocation(new Point(402, 101));
        ((ViewableComponent)withName("g")).setPreferredLocation(new Point(101, 206));
        ((ViewableComponent)withName("p")).setPreferredLocation(new Point(339, 353));
    }
}
