package Lab5;
import java.awt.*;
import simView.*;

public class addModel extends ViewableDigraph // gp model
{

	public addModel()
	{
		super("addModel"); // 캡션 지정
    	
		ViewableAtomic g = new user("user", 10); // 초기 시그마 설정
		ViewableAtomic p = new add("add", 10); // 초기 시그마 설정
    	
		// 노드 추가
		add(g); 
		add(p);
  
		// coupling 생성
		addCoupling(g, "out", p, "in");
		addCoupling(p, "out", g, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("user")).setPreferredLocation(new Point(409, 231));
        ((ViewableComponent)withName("add")).setPreferredLocation(new Point(405, 72));
    }
}
