package Lab10_m;
import java.awt.*;
import simView.*;

public class air_conditioning_system extends ViewableDigraph
{

	public air_conditioning_system()
	{
		super("air_conditioning_system");
    	
		ViewableAtomic u = new user("user", 30); // #여기 30도 넣음
		ViewableDigraph a = new air_conditioner("air_conditioner"); // 여기 중요!
		
		add(u);
		add(a);
  
		addCoupling(u, "out", a, "in");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(988, 646);
        ((ViewableComponent)withName("user")).setPreferredLocation(new Point(261, 249));
        ((ViewableComponent)withName("air_conditioner")).setPreferredLocation(new Point(423, 99));
    }
}
