package Lab10_m;
import java.awt.*;
import simView.*;

public class air_conditioner extends ViewableDigraph
{
	public air_conditioner() { this("air_conditioner"); }
	public air_conditioner(String name)
	{
		super(name);
    	
		addInport("in");
		
		ViewableAtomic c = new controller("controller");
		ViewableAtomic ts = new temp_sensor("temp_sensor", 10);
    	
		add(c);
		add(ts);
  
		addCoupling(this, "in", c, "in1");
		
		addCoupling(c, "out", ts, "in");
		addCoupling(ts, "out", c, "in2");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(354, 344);
        ((ViewableComponent)withName("controller")).setPreferredLocation(new Point(46, 84));
        ((ViewableComponent)withName("temp_sensor")).setPreferredLocation(new Point(51, 250));
    }
}
