package Lab9;
import java.awt.*;
import simView.*;

public class math extends ViewableDigraph
{

	public math()
	{
		this("math");
	}
	
	public math(String name)
	{
		super(name);
		
		// coupled¿« port
		addInport("in");
		addOutport("out");
		
		ViewableAtomic r = new router("router");
		ViewableAtomic a1 = new add("add");
		ViewableAtomic a2 = new acc("acc");
		
		add(r);
		add(a1);
		add(a2);
		
		addCoupling(this, "in", r, "in");
		
		addCoupling(r, "out1", a1, "in");
		addCoupling(r, "out2", a2, "in");
		
		addCoupling(a1, "out", this, "out");
		addCoupling(a2, "out", this, "out");
	}

    
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(526, 359);
        ((ViewableComponent)withName("acc")).setPreferredLocation(new Point(195, 247));
        ((ViewableComponent)withName("router")).setPreferredLocation(new Point(20, 154));
        ((ViewableComponent)withName("add")).setPreferredLocation(new Point(194, 48));
    }
}
